// Client-side constants for the Admin Manage Creatures image flow.
// Mirrors the server-side presets in base44/shared/creatureImages.ts so the
// generate modal and the backend stay in sync (style ids are passed verbatim).

export const IMAGE_STYLE_PRESETS = [
  { id: "semi-realistic", label: "Semi-realistic" },
  { id: "trading-card", label: "Trading-card art" },
  { id: "cartoon", label: "Cartoon" },
  { id: "concept", label: "Concept sketch" },
];

export const DEFAULT_STYLE_PRESET = "semi-realistic";
export const MAX_GENERATE_COUNT = 5;

// ---- Tiered upgrade images (Tier 1–4) ----
// Client mirror of base44/shared/creatureImages.ts so the admin UI can validate
// tier + preview the auto-built prompt without a round-trip. The backend
// re-validates and is the source of truth.
export const MIN_TIER = 1;
export const MAX_TIER = 4;
export const TIERS = [1, 2, 3, 4];
export const MAX_PROMPT_LENGTH = 2000;

export const TIER_LABELS = {
  1: "Tier 1 · Base",
  2: "Tier 2 · Enhanced",
  3: "Tier 3 · Major",
  4: "Tier 4 · Legendary",
};

export const TIER_GUIDANCE = {
  1: "Base — faithful creature representation, clean silhouette, simple/neutral background, card-friendly composition, high-contrast foreground.",
  2: "Enhanced — light armor or elemental accents, slight dynamic pose, maintain legibility for small thumbnails.",
  3: "Major upgrade — elaborate armor/ornamentation, distinct elemental effects, glowing runes, cinematic lighting, high detail while preserving a readable silhouette for small card thumbnails.",
  4: "Legendary — iconic, ornate, highly stylized with particle effects, halo/glow, dramatic lighting, ultra-high detail, unique background, heroic composition.",
};

export const DEFAULT_STYLE_PER_TIER = {
  1: "semi-realistic",
  2: "semi-realistic",
  3: "trading-card",
  4: "trading-card",
};

export function validateTier(t) {
  const n = Math.round(Number(t));
  if (!Number.isFinite(n) || n < MIN_TIER || n > MAX_TIER) {
    throw new Error(`tier must be between ${MIN_TIER} and ${MAX_TIER}`);
  }
  return n;
}

// One-line unique-attack summary for prompt context.
export function summarizeUniqueAttack(creature) {
  const name = (creature?.uniqueAttackName || "").trim();
  if (!name) return "none";
  const pct = clampUniqueAttackPercent(creature?.uniqueAttackPercent || 0);
  const target = creature?.uniqueAttackTarget === "all" ? "all" : "single";
  const effects = Array.isArray(creature?.uniqueAttackEffects)
    ? creature.uniqueAttackEffects.map((e) => String(e).trim()).filter(Boolean)
    : [];
  const eff = effects.length ? ` — applies ${effects.join(", ")}` : "";
  return `${name} — ${pct}% ${target}${eff}`;
}

// Builds the final prompt sent to the image provider. If adminPrompt is
// non-empty it is folded in as "Admin instructions" (autoGenerated=false);
// otherwise the tier guidance + creature metadata + default style preset
// produce a complete tier-appropriate prompt (autoGenerated=true). Over-long
// prompts are truncated to MAX_PROMPT_LENGTH (truncated=true).
export function buildFinalPrompt(args) {
  const tier = validateTier(args.tier);
  const adminPrompt = (args.adminPrompt || "").trim();
  const autoGenerated = !adminPrompt;
  const styleId = args.stylePresetId || DEFAULT_STYLE_PER_TIER[tier] || DEFAULT_STYLE_PRESET;
  const preset = IMAGE_STYLE_PRESETS.find((p) => p.id === styleId) || IMAGE_STYLE_PRESETS[0];
  const tierGuidance = TIER_GUIDANCE[tier] || TIER_GUIDANCE[1];
  const ua = args.uniqueAttackSummary || "none";
  const palette = (args.paletteHint || "match creature theme").trim();
  const anatomy =
    (args.creature?.description || "").trim() ||
    `a creature true to a real ${args.creature?.baseName}`;
  const styleTheme = autoGenerated ? `${preset.modifier} (default for tier)` : preset.modifier;
  const adminClause = adminPrompt ? `Admin instructions: ${adminPrompt}. ` : "";
  const closeup = tier >= 3 ? " Include a close-up detail of the head/armor." : "";

  let finalPrompt =
    `Creature: ${args.creature.baseName}. Tier: ${tier}. Theme/Style: ${styleTheme}. ${adminClause}` +
    `Tier instructions: ${tierGuidance} Visual requirements: full-body, 4:5 aspect ratio, transparent or neutral background suitable for cropping to card, high-res (>=2048 preferred), clear silhouette, no watermarks, avoid logos. ` +
    `Palette: ${palette}. Unique attack: ${ua}. Anatomy: ${anatomy}. ` +
    `Deliverable: 1 finished concept image suitable as a card art guide.${closeup}`;

  let truncated = false;
  if (finalPrompt.length > MAX_PROMPT_LENGTH) {
    finalPrompt = finalPrompt.slice(0, MAX_PROMPT_LENGTH);
    truncated = true;
  }
  return { finalPrompt, autoGenerated, truncated };
}

export const IMAGE_STATUS_META = {
  pending: { label: "Pending", badge: "bg-yellow-500/20 text-yellow-300 border-yellow-500/40" },
  approved: { label: "Approved", badge: "bg-emerald-500/20 text-emerald-300 border-emerald-500/40" },
  rejected: { label: "Rejected", badge: "bg-white/10 text-white/50 border-white/15" },
};

export const AUDIT_ACTION_LABELS = {
  generate_requested: "Generation requested",
  generate_completed: "Image generated",
  generate_failed: "Generation failed",
  image_uploaded: "Image imported",
  image_approved: "Image approved",
  image_rejected: "Image rejected",
  approve_guide: "Approved as guide",
  reject_image: "Rejected",
  default_changed: "Default image changed",
  set_default_tier: "Set default for tier",
  used_in_card_generator: "Used in card generator",
  unique_attack_updated: "Unique Attack updated",
};

// ---- Pure validators (client mirror of base44/shared/creatureImages.ts) ----
// Kept in sync so the admin UI can validate before the round-trip and so the
// unit tests can run without the Deno runtime. The backend re-validates.
export const MIN_UA_PERCENT = 1;
export const MAX_UA_PERCENT = 1000;

export function clampUniqueAttackPercent(p) {
  const n = Math.round(Number(p));
  if (!Number.isFinite(n)) return 0;
  return Math.max(MIN_UA_PERCENT, Math.min(MAX_UA_PERCENT, n));
}

export function validateUniqueAttack(input) {
  const name = (input?.name || "").trim();
  if (!name) return { ok: false, error: "Unique Attack name is required" };
  const rawPct = Number(input?.percent);
  if (!Number.isFinite(rawPct) || rawPct < MIN_UA_PERCENT || rawPct > MAX_UA_PERCENT) {
    return { ok: false, error: `Percent must be between ${MIN_UA_PERCENT} and ${MAX_UA_PERCENT}` };
  }
  const target = input?.target === "all" ? "all" : "single";
  const effects = Array.isArray(input?.effects)
    ? input.effects.map((e) => String(e).trim()).filter(Boolean)
    : [];
  return { ok: true, value: { name, percent: clampUniqueAttackPercent(rawPct), target, effects } };
}

// Localization keys for the new admin surfaces (default to English).
export const CREATURE_IMAGES_I18N = {
  imagesTab: "Images",
  uniqueAttackTab: "Unique Attack",
  detailsTab: "Details",
  generateButton: "Generate Image(s)",
  generateAria: "Generate one or more tiered images for this creature",
  importButton: "Import Image",
  importAria: "Upload an image file for this creature",
  tierLabel: "Tier",
  tierAria: "Target upgrade tier for the generated images",
  promptLabel: "Detailed prompt",
  promptOptional: "Optional — leave blank to use default tier upgrade guidance",
  promptPlaceholder: "Describe the upgrade image, or leave blank to auto-build from tier guidance + creature data…",
  countLabel: "Count",
  styleLabel: "Style",
  guideBadge: "GUIDE",
  defaultForTierBadge: "Default · Tier",
  approveAsGuide: "Approve as Guide",
  approveAria: "Approve this image as a guide for the card generator",
  rejectAria: "Reject this image — it will not be used as a guide",
  setDefaultForTierAria: "Set this guide as the default for its tier",
  useInCardGenerator: "Use in Card Generator",
  useInCardGeneratorAria: "Open the card generator with this guide selected",
  downloadAria: "Download this image",
  approveConfirm: "Approve as guide? This image becomes available to the card generator for this creature + tier.",
  rejectConfirm: "Reject image? This image will remain in history but not be used as a guide.",
  uaHelper: "Damage = floor(baseAttack × percent / 100). Percent must be 1–1000.",
  uaSave: "Save",
  uaCancel: "Cancel",
  noImages: "No images yet. Generate or import one to get started.",
  activityFeed: "Activity",
};