// Server-side helpers for the per-creature image generation/approval flow.
//
// The platform's restricted GenerateImage Core integration is the default image
// provider (no external API key required). A pluggable provider interface is
// exposed so a future provider (e.g. an external image API behind IMAGE_API_KEY)
// can be slotted in by setting the IMAGE_PROVIDER env var.
//
// Used by the generateCreatureImages / approveCreatureImage / rejectCreatureImage
// / setDefaultCreatureImage / uploadCreatureImage / updateCreatureUniqueAttack
// backend functions so the restricted GenerateImage integration is never called
// from the client and all approval/audit logic lives server-side.

import { CREATURE_ANATOMY, CREATURE_STANCES, CREATURE_COLOR_PALETTES } from "./cardArt.ts";

export const IMAGE_STYLE_PRESETS = [
  { id: "semi-realistic", label: "Semi-realistic", modifier: "semi-realistic digital painting, cinematic lighting, highly detailed" },
  { id: "trading-card", label: "Trading-card art", modifier: "mystical fantasy trading-card art style, rich painterly saturated colors, dramatic rim lighting" },
  { id: "cartoon", label: "Cartoon", modifier: "bold cartoon illustration, clean line art, flat vibrant colors" },
  { id: "concept", label: "Concept sketch", modifier: "concept-art sketch, painterly strokes, muted palette" },
];

export const DEFAULT_STYLE_PRESET = "semi-realistic";

export const MAX_GENERATE_COUNT = 5;

export interface CreatureRecord {
  id: string;
  baseName: string;
  category?: string;
  description?: string;
}

export interface GeneratedImage {
  url: string;
  storageKey?: string;
  meta?: Record<string, unknown>;
}

export interface ImageProvider {
  name: string;
  generateImages(
    base44: any,
    prompt: string,
    count: number,
    refs?: string[]
  ): Promise<GeneratedImage[]>;
}

// Default provider: the platform's built-in GenerateImage integration. One call
// per image (the integration returns a single image); we run them in parallel.
const base44CoreProvider: ImageProvider = {
  name: "base44-core",
  async generateImages(base44, prompt, count, _refs) {
    const results = await Promise.all(
      Array.from({ length: count }, () =>
        base44.asServiceRole.integrations.Core.GenerateImage({ prompt }).then(
          ({ url }: { url: string }) => ({ url, storageKey: url }) as GeneratedImage
        )
      )
    );
    return results;
  },
};

// Resolve the active provider from the IMAGE_PROVIDER env var (future: external
// image API behind IMAGE_API_KEY). Currently only 'base44-core' is implemented.
export function getImageProvider(): ImageProvider {
  const configured = (Deno.env.get("IMAGE_PROVIDER") || "base44-core").toLowerCase();
  if (configured && configured !== "base44-core") {
    // Future: wire an external provider here. Until then, fall back to core so
    // a misconfigured env var never breaks generation.
    console.warn(`[creatureImages] unknown IMAGE_PROVIDER '${configured}' — falling back to base44-core`);
  }
  return base44CoreProvider;
}

const randomFrom = <T,>(arr: T[]): T => arr[Math.floor(Math.random() * arr.length)];

// Build a creature-art prompt from an admin-supplied prompt, the creature's
// anatomy/description, and the chosen style preset. Falls back to the shared
// anatomy dictionary when the creature has no admin-authored description.
export function buildCreatureImagePrompt(creature: CreatureRecord, userPrompt: string, stylePresetId: string): string {
  const preset = IMAGE_STYLE_PRESETS.find((p) => p.id === stylePresetId) || IMAGE_STYLE_PRESETS[0];
  const stance = randomFrom(CREATURE_STANCES);
  const palette = randomFrom(CREATURE_COLOR_PALETTES);
  const anatomy = creature.description?.trim() || CREATURE_ANATOMY[creature.baseName] || `a creature true to a real ${creature.baseName}`;
  const base = userPrompt.trim() || `A ${creature.baseName}, ${stance}, ${palette} color scheme, full-body creature illustration.`;
  return `${base} Anatomy: ${anatomy}. Style: ${preset.modifier}. The creature is the clear focal point, sharply rendered against its background. No text, no border, no frame.`;
}

// ---- Tiered upgrade images (Tier 1–4) ----
// Each creature can have concept/guide images per upgrade tier. Admins may supply
// a detailed prompt; if they leave it blank, buildFinalPrompt auto-builds a
// tier-appropriate prompt from tier guidance + creature metadata and sets
// promptAutoGenerated=true. Approved guides (isGuide=true) feed the card
// generator's Choose Guide step.
export const MIN_TIER = 1;
export const MAX_TIER = 4;
export const TIERS = [1, 2, 3, 4];
export const MAX_PROMPT_LENGTH = 2000;

export const TIER_GUIDANCE: Record<number, string> = {
  1: "Base — faithful creature representation, clean silhouette, simple/neutral background, card-friendly composition, high-contrast foreground.",
  2: "Enhanced — light armor or elemental accents, slight dynamic pose, maintain legibility for small thumbnails.",
  3: "Major upgrade — elaborate armor/ornamentation, distinct elemental effects, glowing runes, cinematic lighting, high detail while preserving a readable silhouette for small card thumbnails.",
  4: "Legendary — iconic, ornate, highly stylized with particle effects, halo/glow, dramatic lighting, ultra-high detail, unique background, heroic composition.",
};

// Default style preset when the admin does not choose one, per tier.
export const DEFAULT_STYLE_PER_TIER: Record<number, string> = {
  1: "semi-realistic",
  2: "semi-realistic",
  3: "trading-card",
  4: "trading-card",
};

export function validateTier(t: unknown): number {
  const n = Math.round(Number(t));
  if (!Number.isFinite(n) || n < MIN_TIER || n > MAX_TIER) {
    throw new Error(`tier must be between ${MIN_TIER} and ${MAX_TIER}`);
  }
  return n;
}

// One-line summary of a creature's unique attack for prompt context.
export function summarizeUniqueAttack(creature: any): string {
  const name = (creature?.uniqueAttackName || "").trim();
  if (!name) return "none";
  const pct = clampUniqueAttackPercent(creature?.uniqueAttackPercent || 0);
  const target = creature?.uniqueAttackTarget === "all" ? "all" : "single";
  const effects = Array.isArray(creature?.uniqueAttackEffects)
    ? creature.uniqueAttackEffects.map((e: string) => String(e).trim()).filter(Boolean)
    : [];
  const eff = effects.length ? ` — applies ${effects.join(", ")}` : "";
  return `${name} — ${pct}% ${target}${eff}`;
}

export interface BuildPromptArgs {
  creature: CreatureRecord;
  tier: number;
  stylePresetId?: string;
  adminPrompt?: string;
  uniqueAttackSummary?: string;
  paletteHint?: string;
}

export interface BuildPromptResult {
  finalPrompt: string;
  autoGenerated: boolean;
  truncated: boolean;
}

// Builds the final prompt sent to the image provider using the shared template.
// If adminPrompt is non-empty it is folded in as "Admin instructions" and
// autoGenerated is false. If adminPrompt is empty, the tier guidance + creature
// metadata + default style preset produce a complete tier-appropriate prompt and
// autoGenerated is true. Over-long prompts are truncated to MAX_PROMPT_LENGTH
// with a logged warning and truncated=true.
export function buildFinalPrompt(args: BuildPromptArgs): BuildPromptResult {
  const tier = validateTier(args.tier);
  const adminPrompt = (args.adminPrompt || "").trim();
  const autoGenerated = !adminPrompt;
  const styleId = args.stylePresetId || DEFAULT_STYLE_PER_TIER[tier] || DEFAULT_STYLE_PRESET;
  const preset = IMAGE_STYLE_PRESETS.find((p) => p.id === styleId) || IMAGE_STYLE_PRESETS[0];
  const tierGuidance = TIER_GUIDANCE[tier] || TIER_GUIDANCE[1];
  const ua = args.uniqueAttackSummary || "none";
  const palette = (args.paletteHint || "match creature theme").trim();
  const anatomy = args.creature.description?.trim() || CREATURE_ANATOMY[args.creature.baseName] || `a creature true to a real ${args.creature.baseName}`;
  const styleTheme = autoGenerated ? `${preset.modifier} (default for tier)` : preset.modifier;

  const adminClause = adminPrompt ? `Admin instructions: ${adminPrompt}. ` : "";
  const closeup = tier >= 3 ? " Include a close-up detail of the head/armor." : "";

  let finalPrompt =
    `Creature: ${args.creature.baseName}. Tier: ${tier}. Theme/Style: ${styleTheme}. ${adminClause}` +
    `Tier instructions: ${tierGuidance} Visual requirements: full-body, 4:5 aspect ratio, transparent or neutral background suitable for cropping to card, high-res (>=2048 preferred), clear silhouette, no watermarks, avoid logos. ` +
    `Palette: ${palette}. Unique attack: ${ua}. Anatomy: ${anatomy}. ` +
    `Deliverable: 1 finished concept image suitable as a card art guide.${closeup}`;

  let truncated = false;
  if (finalPrompt.length > MAX_PROMPT_LENGTH) {
    console.warn(`[creatureImages] final prompt truncated from ${finalPrompt.length} to ${MAX_PROMPT_LENGTH} chars`);
    finalPrompt = finalPrompt.slice(0, MAX_PROMPT_LENGTH);
    truncated = true;
  }
  return { finalPrompt, autoGenerated, truncated };
}

// Convenience wrapper for the auto-prompt path (no admin prompt).
export function buildDefaultPrompt(args: Omit<BuildPromptArgs, "adminPrompt">): BuildPromptResult {
  return buildFinalPrompt({ ...args, adminPrompt: "" });
}

// ---- Unique Attack validation ----
export const MIN_UA_PERCENT = 1;
export const MAX_UA_PERCENT = 1000;

export function clampUniqueAttackPercent(p: number): number {
  const n = Math.round(Number(p));
  if (!Number.isFinite(n)) return 0;
  return Math.max(MIN_UA_PERCENT, Math.min(MAX_UA_PERCENT, n));
}

export interface UniqueAttackInput {
  name: string;
  percent: number;
  target: "single" | "all";
  effects: string[];
}

export function validateUniqueAttack(input: Partial<UniqueAttackInput>): { ok: true; value: UniqueAttackInput } | { ok: false; error: string } {
  const name = (input.name || "").trim();
  if (!name) return { ok: false, error: "Unique Attack name is required" };
  const rawPct = Number(input.percent);
  if (!Number.isFinite(rawPct) || rawPct < MIN_UA_PERCENT || rawPct > MAX_UA_PERCENT) {
    return { ok: false, error: `Percent must be between ${MIN_UA_PERCENT} and ${MAX_UA_PERCENT}` };
  }
  const target = input.target === "all" ? "all" : "single";
  const effects = Array.isArray(input.effects)
    ? input.effects.map((e) => String(e).trim()).filter(Boolean)
    : [];
  return { ok: true, value: { name, percent: clampUniqueAttackPercent(rawPct), target, effects } };
}

// ---- Audit logging ----
export async function logCreatureEvent(
  base44: any,
  entry: { creatureId: string; imageId?: string; action: string; userId: string; userName?: string; note?: string }
) {
  try {
    await base44.asServiceRole.entities.CreatureAuditLog.create({
      creatureId: entry.creatureId,
      imageId: entry.imageId || "",
      action: entry.action,
      userId: entry.userId,
      userName: entry.userName || "",
      note: entry.note || "",
    });
  } catch (err) {
    // Audit logging is best-effort — never fail the main operation because of it.
    console.error("[creatureImages] audit log failed", err);
  }
}