// Server-authoritative power-up definitions for the replenish flow. The client
// (src/lib/gameConstants.js POWER_DEFINITIONS) owns the full UI catalog; this
// holds only the security-relevant fields the backend must NOT trust from the
// client: the coin cost and which User field marks the power as used/owned.
// Keep in sync when adding a power-up — a missing key here makes replenish fail
// closed (rejected) rather than trusting a client-supplied cost.
export const POWER_DEFS: Record<string, { replenishCost: number; cooldownType: string; usesField?: string; usedAtField?: string }> = {
  burn: { replenishCost: 10000, cooldownType: 'daily', usedAtField: 'burnPowerUsedAt' },
  doubleAttack: { replenishCost: 10000, cooldownType: 'daily', usedAtField: 'doubleAttackPowerUsedAt' },
  ignoreDefense: { replenishCost: 10000, cooldownType: 'daily', usedAtField: 'ignoreDefensePowerUsedAt' },
  trueDamage: { replenishCost: 10000, cooldownType: 'daily', usedAtField: 'trueDamagePowerUsedAt' },
  critHit: { replenishCost: 10000, cooldownType: 'daily', usedAtField: 'critHitPowerUsedAt' },
  doubleBonusDamage: { replenishCost: 10000, cooldownType: 'dailyMulti', usesField: 'doubleBonusDamagePowerUsesToday' },
  attackTwice: { replenishCost: 100000, cooldownType: 'weekly', usedAtField: 'attackTwicePowerUsedAt' },
  defense: { replenishCost: 10000, cooldownType: 'daily', usedAtField: 'defensePowerUsedAt' },
  block: { replenishCost: 5000, cooldownType: 'dailyMulti', usesField: 'blockPowerUsesToday' },
  halfAttack: { replenishCost: 10000, cooldownType: 'dailyMulti', usesField: 'halfAttackPowerUsesToday' },
  doubleDefense2Turns: { replenishCost: 10000, cooldownType: 'daily', usedAtField: 'doubleDefense2TurnsPowerUsedAt' },
  tripleDefense1Turn: { replenishCost: 10000, cooldownType: 'daily', usedAtField: 'tripleDefense1TurnPowerUsedAt' },
  shield25: { replenishCost: 10000, cooldownType: 'daily', usedAtField: 'shield25PowerUsedAt' },
  negateNextAttack: { replenishCost: 10000, cooldownType: 'daily', usedAtField: 'negateNextAttackPowerUsedAt' },
  reduceDamage50: { replenishCost: 10000, cooldownType: 'daily', usedAtField: 'reduceDamage50PowerUsedAt' },
  reflectDamage25: { replenishCost: 10000, cooldownType: 'daily', usedAtField: 'reflectDamagePowerUsedAt' },
  regen10Percent3Turns: { replenishCost: 10000, cooldownType: 'daily', usedAtField: 'regenPowerUsedAt' },
  surviveWith1HP: { replenishCost: 50000, cooldownType: 'weekly', usedAtField: 'surviveWith1HPPowerUsedAt' },
  heal20: { replenishCost: 10000, cooldownType: 'daily', usedAtField: 'heal20PowerUsedAt' },
  heal50: { replenishCost: 30000, cooldownType: 'daily', usedAtField: 'heal50PowerUsedAt' },
  fullRestore: { replenishCost: 100000, cooldownType: 'weekly', usedAtField: 'fullRestorePowerUsedAt' },
  maxHPBoost25: { replenishCost: 10000, cooldownType: 'daily', usedAtField: 'maxHPBoostPowerUsedAt' },
  restoreOnDefeat: { replenishCost: 10000, cooldownType: 'daily', usedAtField: 'restoreOnDefeatPowerUsedAt' },
  healOnDamage10_3Turns: { replenishCost: 50000, cooldownType: 'weekly', usedAtField: 'healOnDamagePowerUsedAt' },
  reshuffle: { replenishCost: 10000, cooldownType: 'daily', usedAtField: 'reshufflePowerUsedAt' },
  swapActiveCard50HP: { replenishCost: 10000, cooldownType: 'daily', usedAtField: 'swapCardPowerUsedAt' },
  returnOpponentCard: { replenishCost: 10000, cooldownType: 'daily', usedAtField: 'returnOpponentCardPowerUsedAt' },
  duplicateCard: { replenishCost: 50000, cooldownType: 'weekly', usedAtField: 'duplicateCardPowerUsedAt' },
  t2Upgrade: { replenishCost: 50000, cooldownType: 'weekly', usedAtField: 't2UpgradePowerUsedAt' },
  t3Upgrade: { replenishCost: 75000, cooldownType: 'weekly', usedAtField: 't3UpgradePowerUsedAt' },
  t4Upgrade: { replenishCost: 100000, cooldownType: 'weekly', usedAtField: 't4UpgradePowerUsedAt' },
  upgradeTierOneBattle: { replenishCost: 10000, cooldownType: 'daily', usedAtField: 'upgradeTierPowerUsedAt' },
  maximizeAttackTurn: { replenishCost: 10000, cooldownType: 'weekly', usedAtField: 'maximizeAttackPowerUsedAt' },
  maximizeDefenseTurn: { replenishCost: 10000, cooldownType: 'weekly', usedAtField: 'maximizeDefensePowerUsedAt' },
  increaseAllStats20: { replenishCost: 50000, cooldownType: 'premium', usedAtField: 'increaseAllStatsOwned' },
  increaseBonusDamage100: { replenishCost: 5000, cooldownType: 'dailyMulti', usesField: 'bonusDamage100PowerUsesToday' },
  timeFreeze: { replenishCost: 50000, cooldownType: 'premium', usedAtField: 'timeFreezeOwned' },
  lastStand: { replenishCost: 50000, cooldownType: 'premium', usedAtField: 'lastStandOwned' },
  berserkerRage: { replenishCost: 50000, cooldownType: 'premium', usedAtField: 'berserkerRageOwned' },
  divineProtection: { replenishCost: 50000, cooldownType: 'premium', usedAtField: 'divineProtectionOwned' },
  phoenixRebirth: { replenishCost: 50000, cooldownType: 'premium', usedAtField: 'phoenixRebirthOwned' },
  deckSurge: { replenishCost: 50000, cooldownType: 'premium', usedAtField: 'deckSurgeOwned' },
};