import React, { useState } from "react";
import { Check, X, Star, Download, Wand2 } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { Image } from "@/components/ui/image";
import { IMAGE_STATUS_META, TIER_LABELS, CREATURE_IMAGES_I18N } from "@/lib/creatureImages";
import ConfirmNoteModal from "./ConfirmNoteModal";

function fmtDate(ts) {
  if (!ts) return "";
  try {
    return new Date(ts).toLocaleString();
  } catch {
    return ts;
  }
}

// One image in the gallery: thumbnail + tier/status/guide badges + metadata +
// actions. Approve = "Approve as Guide" (opens a confirm-with-note modal);
// Reject opens its own confirm. Set Default for Tier and Use in Card Generator
// act immediately. `pending` images without a url yet show a generating spinner.
export default function CreatureImageTile({ image, creature, onApprove, onReject, onSetDefault, busy }) {
  const navigate = useNavigate();
  const [confirm, setConfirm] = useState(null); // { kind }
  const meta = IMAGE_STATUS_META[image.status] || IMAGE_STATUS_META.pending;
  const isDefaultForTier = !!image.isDefaultForTier;
  const isGuide = !!image.isGuide;
  const generating = !image.url;

  const runConfirm = async (note) => {
    if (confirm?.kind === "approve") await onApprove(note);
    else if (confirm?.kind === "reject") await onReject(note);
    setConfirm(null);
  };

  const useInCardGenerator = () => {
    const baseName = encodeURIComponent(creature?.baseName || "");
    navigate(`/generate?guide=${image.id}&creature=${baseName}&tier=${image.tier || 1}`);
  };

  return (
    <div className="bg-white/5 rounded-xl overflow-hidden border border-white/10">
      <div className="relative aspect-square bg-black/30">
        {generating ? (
          <div className="absolute inset-0 flex items-center justify-center text-white/50 text-xs">
            <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
          </div>
        ) : (
          <Image src={image.url} alt={image.prompt || "creature image"} className="w-full h-full" />
        )}
        <span className={`absolute top-1.5 left-1.5 text-[10px] font-bold px-1.5 py-0.5 rounded border ${meta.badge}`}>
          {meta.label}
        </span>
        <span className="absolute top-1.5 left-1.5 mt-5 text-[10px] font-bold px-1.5 py-0.5 rounded bg-black/60 text-white/80 border border-white/10">
          {TIER_LABELS[image.tier] || `Tier ${image.tier || 1}`}
        </span>
        {isGuide && (
          <span className="absolute top-1.5 right-1.5 text-[10px] font-bold px-1.5 py-0.5 rounded bg-fuchsia-600 text-white flex items-center gap-0.5">
            <Wand2 className="w-2.5 h-2.5" /> {CREATURE_IMAGES_I18N.guideBadge}
          </span>
        )}
        {isDefaultForTier && (
          <span className="absolute top-1.5 right-1.5 mt-5 text-[10px] font-bold px-1.5 py-0.5 rounded bg-amber-500 text-black flex items-center gap-0.5">
            <Star className="w-2.5 h-2.5 fill-black" /> {CREATURE_IMAGES_I18N.defaultForTierBadge} {image.tier}
          </span>
        )}
      </div>
      <div className="px-2 py-1.5 space-y-1">
        <div className="flex items-center justify-between text-[10px] text-white/40">
          <span>{image.generatedBy === "manual" ? "Manual upload" : image.generatedBy || "—"}</span>
          {image.url && (
            <a href={image.url} target="_blank" rel="noreferrer" download aria-label={CREATURE_IMAGES_I18N.downloadAria} className="text-white/40 hover:text-white">
              <Download className="w-3 h-3" />
            </a>
          )}
        </div>
        <div className="text-[10px] text-white/30">{fmtDate(image.created_date)}</div>
        {image.authorName && <div className="text-[10px] text-white/30">by {image.authorName}</div>}
        {image.promptAutoGenerated && <div className="text-[10px] text-cyan-300/70">auto-built prompt</div>}
        {image.errorMessage && <div className="text-[10px] text-red-400">failed: {image.errorMessage}</div>}
        {image.notes && <div className="text-[10px] text-white/40 truncate">{image.notes}</div>}
      </div>
      {!generating && (
        <div className="flex flex-col gap-1 px-2 pb-2">
          <div className="flex gap-1">
            {image.status !== "approved" && (
              <button
                onClick={() => setConfirm({ kind: "approve" })}
                disabled={busy}
                aria-label={CREATURE_IMAGES_I18N.approveAria}
                className="flex-1 flex items-center justify-center gap-1 bg-emerald-600/80 hover:bg-emerald-600 text-white text-[11px] font-semibold py-1.5 rounded-md disabled:opacity-60"
              >
                <Check className="w-3 h-3" /> {CREATURE_IMAGES_I18N.approveAsGuide}
              </button>
            )}
            {image.status !== "rejected" && (
              <button
                onClick={() => setConfirm({ kind: "reject" })}
                disabled={busy}
                aria-label={CREATURE_IMAGES_I18N.rejectAria}
                className="flex-1 flex items-center justify-center gap-1 bg-red-700/70 hover:bg-red-700 text-white text-[11px] font-semibold py-1.5 rounded-md disabled:opacity-60"
              >
                <X className="w-3 h-3" /> Reject
              </button>
            )}
          </div>
          <div className="flex gap-1">
            <button
              onClick={onSetDefault}
              disabled={busy || !isGuide}
              aria-label={CREATURE_IMAGES_I18N.setDefaultForTierAria}
              className={`flex items-center justify-center gap-1 px-2 py-1.5 rounded-md text-[11px] ${
                isDefaultForTier ? "bg-amber-500/20 text-amber-300" : "bg-white/10 text-white hover:bg-white/20"
              } disabled:opacity-40`}
            >
              <Star className={`w-3 h-3 ${isDefaultForTier ? "fill-amber-300" : ""}`} /> Default · T{image.tier}
            </button>
            {isGuide && (
              <button
                onClick={useInCardGenerator}
                aria-label={CREATURE_IMAGES_I18N.useInCardGeneratorAria}
                className="flex-1 flex items-center justify-center gap-1 bg-fuchsia-600/80 hover:bg-fuchsia-600 text-white text-[11px] font-semibold py-1.5 rounded-md"
              >
                <Wand2 className="w-3 h-3" /> {CREATURE_IMAGES_I18N.useInCardGenerator}
              </button>
            )}
          </div>
        </div>
      )}
      {confirm && (
        <ConfirmNoteModal
          title={confirm.kind === "approve" ? "Approve as guide" : "Reject image"}
          message={confirm.kind === "approve" ? CREATURE_IMAGES_I18N.approveConfirm : CREATURE_IMAGES_I18N.rejectConfirm}
          confirmLabel={confirm.kind === "approve" ? "Approve" : "Reject"}
          confirmClass={confirm.kind === "approve" ? "bg-emerald-600" : "bg-red-700"}
          noteLabel="Optional note"
          onConfirm={runConfirm}
          onClose={() => setConfirm(null)}
        />
      )}
    </div>
  );
}