import React, { useState } from "react";
import { Sparkles } from "lucide-react";
import { base44 } from "@/api/base44Client";
import ModalShell from "./ModalShell";
import DrawerPicker from "@/components/common/DrawerPicker";
import {
  IMAGE_STYLE_PRESETS,
  DEFAULT_STYLE_PRESET,
  MAX_GENERATE_COUNT,
  TIERS,
  TIER_LABELS,
  TIER_GUIDANCE,
  DEFAULT_STYLE_PER_TIER,
  buildFinalPrompt,
  summarizeUniqueAttack,
  CREATURE_IMAGES_I18N,
} from "@/lib/creatureImages";

// Generate modal: Tier selector (1–4), optional detailed prompt, count (1–5),
// style preset. The prompt is OPTIONAL — when blank the server auto-builds a
// tier-appropriate prompt from tier guidance + creature metadata. A live
// preview of the final prompt is shown so the admin sees exactly what will be
// sent. Calls the generateCreatureImages backend function (server-side image
// generation; never the client GenerateImage).
export default function GenerateImagesModal({ creature, onClose, onGenerated }) {
  const [tier, setTier] = useState(1);
  const [prompt, setPrompt] = useState("");
  const [count, setCount] = useState(1);
  const [style, setStyle] = useState(DEFAULT_STYLE_PER_TIER[1] || DEFAULT_STYLE_PRESET);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");

  const preview = (() => {
    try {
      return buildFinalPrompt({
        creature,
        tier,
        stylePresetId: style,
        adminPrompt: prompt,
        uniqueAttackSummary: summarizeUniqueAttack(creature),
      });
    } catch {
      return null;
    }
  })();

  const generate = async () => {
    if (busy) return;
    setBusy(true);
    setError("");
    try {
      await base44.functions.invoke("generateCreatureImages", {
        creatureId: creature.id,
        tier,
        prompt: prompt.trim(),
        count,
        style,
      });
      onGenerated();
      onClose();
    } catch (err) {
      setError(err?.message || "Generation failed");
    } finally {
      setBusy(false);
    }
  };

  const countOptions = Array.from({ length: MAX_GENERATE_COUNT }, (_, i) => ({ value: String(i + 1), label: `${i + 1} image${i ? "s" : ""}` }));
  const styleOptions = IMAGE_STYLE_PRESETS.map((p) => ({ value: p.id, label: p.label }));
  const tierOptions = TIERS.map((t) => ({ value: String(t), label: TIER_LABELS[t] }));

  return (
    <ModalShell title="Generate tiered upgrade images" onClose={onClose}>
      <div className="space-y-3">
        <div>
          <label className="text-white/60 text-xs mb-1 block">{CREATURE_IMAGES_I18N.tierLabel}</label>
          <div className="flex flex-wrap gap-1.5">
            {TIERS.map((t) => (
              <button
                key={t}
                onClick={() => setTier(t)}
                aria-label={`${CREATURE_IMAGES_I18N.tierLabel} ${t}`}
                className={`px-2.5 py-1.5 rounded-lg text-xs font-semibold ${
                  tier === t ? "bg-purple-600 text-white" : "bg-white/5 text-white/60"
                }`}
              >
                {TIER_LABELS[t]}
              </button>
            ))}
          </div>
          <p className="text-white/35 text-[10px] mt-1">{TIER_GUIDANCE[tier]}</p>
        </div>

        <div>
          <label className="text-white/60 text-xs mb-1 block">{CREATURE_IMAGES_I18N.promptLabel}</label>
          <textarea
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            rows={3}
            placeholder={CREATURE_IMAGES_I18N.promptPlaceholder}
            className="w-full bg-white/10 rounded-md px-3 py-2 text-sm outline-none resize-none"
          />
          <p className="text-white/35 text-[10px] mt-1">{CREATURE_IMAGES_I18N.promptOptional}</p>
        </div>

        <div className="flex gap-2 items-center">
          <div className="flex-1 bg-white/10 rounded-md px-3 py-2">
            <div className="text-white/40 text-[10px] mb-0.5">{CREATURE_IMAGES_I18N.countLabel}</div>
            <DrawerPicker label={CREATURE_IMAGES_I18N.countLabel} options={countOptions} value={String(count)} onSelect={(v) => setCount(Number(v))} />
          </div>
          <div className="flex-1 bg-white/10 rounded-md px-3 py-2">
            <div className="text-white/40 text-[10px] mb-0.5">{CREATURE_IMAGES_I18N.styleLabel}</div>
            <DrawerPicker label={CREATURE_IMAGES_I18N.styleLabel} options={styleOptions} value={style} onSelect={setStyle} />
          </div>
        </div>

        {preview && (
          <details className="bg-white/5 rounded-md px-3 py-2">
            <summary className="text-white/50 text-[11px] cursor-pointer">
              Final prompt preview {preview.autoGenerated ? "(auto-built)" : "(admin prompt)"}
            </summary>
            <p className="text-white/60 text-[10px] mt-1 whitespace-pre-wrap break-words">{preview.finalPrompt}</p>
          </details>
        )}

        {error && <p className="text-red-400 text-xs">{error}</p>}
        <button
          onClick={generate}
          disabled={busy}
          aria-label={CREATURE_IMAGES_I18N.generateAria}
          className="w-full flex items-center justify-center gap-2 bg-purple-600 hover:bg-purple-500 disabled:opacity-50 rounded-lg py-3 text-sm font-semibold text-white"
        >
          {busy ? (
            <>
              <div className="w-4 h-4 border-2 border-white/40 border-t-white rounded-full animate-spin" /> Generating…
            </>
          ) : (
            <>
              <Sparkles className="w-4 h-4" /> {CREATURE_IMAGES_I18N.generateButton}
            </>
          )}
        </button>
      </div>
    </ModalShell>
  );
}