import { createClientFromRequest } from 'npm:@base44/sdk@0.8.40';
import { validateTier, logCreatureEvent } from '../../shared/creatureImages.ts';

// POST { creatureId, url, tier, prompt }
// Records a manually-uploaded image (the client uploads the file via the
// UploadPublicFile integration first, then passes the resulting url here).
// `tier` is optional (defaults to 1); `prompt` is optional metadata. Creates a
// pending CreatureImage record with generatedBy='manual'. Does NOT create a
// card. Returns { image }.
//
// Admin-only.
Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });
    if (user.role !== 'admin') return Response.json({ error: 'Forbidden' }, { status: 403 });

    const { creatureId, url, tier, prompt } = await req.json().catch(() => ({}));
    if (!creatureId) return Response.json({ error: 'creatureId is required' }, { status: 400 });
    const imageUrl = (url || '').trim();
    if (!imageUrl) return Response.json({ error: 'url is required' }, { status: 400 });
    let tierNum;
    try { tierNum = validateTier(tier || 1); }
    catch (e) { return Response.json({ error: (e as Error).message }, { status: 400 }); }
    const promptText = (prompt || '').trim();

    const creature = await base44.entities.Creature.get(creatureId).catch(() => null);
    if (!creature) return Response.json({ error: 'creature not found' }, { status: 404 });

    const image = await base44.asServiceRole.entities.CreatureImage.create({
      creatureId,
      tier: tierNum,
      url: imageUrl,
      storageKey: imageUrl,
      status: 'pending',
      generatedBy: 'manual',
      authorId: user.id,
      authorName: user.fullName || user.email || '',
      prompt: promptText,
      promptAutoGenerated: false,
      isDefault: false,
      isGuide: false,
      isDefaultForTier: false,
    });
    await logCreatureEvent(base44, {
      creatureId,
      imageId: image.id,
      action: 'image_uploaded',
      userId: user.id,
      userName: user.fullName || user.email || '',
      note: `tier ${tierNum}`,
    });
    return Response.json({ image });
  } catch (error) {
    console.error('uploadCreatureImage error', error);
    return Response.json({ error: (error as Error).message }, { status: 500 });
  }
});