import { createClientFromRequest } from 'npm:@base44/sdk@0.8.40';
import {
  getImageProvider,
  buildFinalPrompt,
  summarizeUniqueAttack,
  validateTier,
  logCreatureEvent,
  MAX_GENERATE_COUNT,
  DEFAULT_STYLE_PRESET,
} from '../../shared/creatureImages.ts';

// POST { creatureId, tier, prompt, count, style }
// Generates 1–5 tiered upgrade images for an existing creature WITHOUT creating
// any card. `tier` is required (1–4). `prompt` is OPTIONAL: when non-empty it is
// folded into the final prompt as admin instructions; when empty the server
// auto-builds a tier-appropriate prompt from tier guidance + creature metadata
// (promptAutoGenerated=true). The final prompt is stored on each image record.
// Per-image failures are kept as pending records with errorMessage populated.
// Returns { images, generated, failed, promptAutoGenerated }.
//
// Admin-only.
Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });
    if (user.role !== 'admin') return Response.json({ error: 'Forbidden' }, { status: 403 });

    const { creatureId, prompt, count, style, tier } = await req.json().catch(() => ({}));
    if (!creatureId) return Response.json({ error: 'creatureId is required' }, { status: 400 });
    let tierNum;
    try { tierNum = validateTier(tier || 1); }
    catch (e) { return Response.json({ error: (e as Error).message }, { status: 400 }); }
    const adminPrompt = (prompt || '').trim();
    const n = Math.max(1, Math.min(MAX_GENERATE_COUNT, Math.round(Number(count) || 1)));
    const stylePreset = style || DEFAULT_STYLE_PRESET;

    const creature = await base44.entities.Creature.get(creatureId).catch(() => null);
    if (!creature) return Response.json({ error: 'creature not found' }, { status: 404 });

    const { finalPrompt, autoGenerated, truncated } = buildFinalPrompt({
      creature,
      tier: tierNum,
      stylePresetId: stylePreset,
      adminPrompt,
      uniqueAttackSummary: summarizeUniqueAttack(creature),
    });

    const provider = getImageProvider();

    // 1. Create pending records up-front so the admin UI can show them immediately.
    const records = await Promise.all(
      Array.from({ length: n }, () =>
        base44.asServiceRole.entities.CreatureImage.create({
          creatureId,
          tier: tierNum,
          url: '',
          storageKey: '',
          status: 'pending',
          generatedBy: provider.name,
          authorId: user.id,
          authorName: user.fullName || user.email || '',
          prompt: finalPrompt,
          promptAutoGenerated: autoGenerated,
          stylePreset,
          isDefault: false,
          isGuide: false,
          isDefaultForTier: false,
          notes: truncated ? 'prompt auto-truncated' : '',
        })
      )
    );
    await logCreatureEvent(base44, {
      creatureId,
      action: 'generate_requested',
      userId: user.id,
      userName: user.fullName || user.email || '',
      note: `tier ${tierNum}, ${n} image(s), style=${stylePreset}, auto_prompt=${autoGenerated}, provider=${provider.name}`,
    });

    // 2. Generate each image in parallel and fill its record. A failure marks
    //    the record with errorMessage but keeps it (pending) for audit.
    await Promise.all(
      records.map((rec) =>
        provider
          .generateImages(base44, finalPrompt, 1)
          .then(async (out) => {
            const img = out[0];
            if (!img?.url) throw new Error('provider returned no url');
            await base44.asServiceRole.entities.CreatureImage.update(rec.id, {
              url: img.url,
              storageKey: img.storageKey || img.url,
            });
            await logCreatureEvent(base44, {
              creatureId,
              imageId: rec.id,
              action: 'generate_completed',
              userId: user.id,
              userName: user.fullName || user.email || '',
              note: `tier ${tierNum}`,
            });
          })
          .catch(async (err) => {
            await base44.asServiceRole.entities.CreatureImage.update(rec.id, {
              errorMessage: String(err?.message || err),
            });
            await logCreatureEvent(base44, {
              creatureId,
              imageId: rec.id,
              action: 'generate_failed',
              userId: user.id,
              userName: user.fullName || user.email || '',
              note: String(err?.message || err),
            });
          })
      )
    );

    const finalImages = await base44.asServiceRole.entities.CreatureImage.filter({ creatureId });
    const ids = new Set(records.map((r) => r.id));
    const succeeded = finalImages.filter((i) => ids.has(i.id) && i.url).length;
    const failed = n - succeeded;
    return Response.json({ images: finalImages, generated: succeeded, failed, promptAutoGenerated: autoGenerated });
  } catch (error) {
    console.error('generateCreatureImages error', error);
    return Response.json({ error: (error as Error).message }, { status: 500 });
  }
});